### ISSUE TITLE
Add dataset validator

### ISSUE THREAD

**Issue by KennethEnevoldsen** [centre-for-humanities-computing/danish-foundation-models#266]
We discussed creating a dataset validator.

This issue here is to discuss how we want the standard format to be. Currently we have done it like this:

```
{
    "id": "...",                          # MANDATORY: source-specific identifier
    "text": "foo",                    # MANDATORY: textual content of the document
    "source": "...",                  # MANDATORY: source of the data, such as peS2o, common-crawl, etc.
    "added": "...",                   # OPTIONAL: timestamp we acquired this data (time file was created), specified as 
                                              # YYYY-MM-DDTHH:MM:SS.TIMEZONE e.g 2021-04-13T12:52:46.000Z
    "created": "..."                  # OPTIONAL: timestamp when orig document was created (best-guess if not available), 
                                              # should be specified as a range; 
                                              # "YYYY-MM-DDTHH:MM:SS.TIMEZONE, YYYY-MM-DDTHH:MM:SS.TIMEZONE"
    "metadata": {                   # OPTIONAL: source-specific metadata
	"sub-source": "...",       # OPTIONAL: E.g. "newspaper_ocr"
         ...
     }        
}
```

I would like to add a license at least here as well and discuss the level of "source"/"sub-source" (e.g. for filtering domains etc.).

I don't mind creating this as long as we find the time to agree on a reasonable format

**Comment by peterbjorgensen** [comment]
I think we should add the requirement that "source": "..." is the same as the top level directory, i.e. `data/{source}/documents/part1.jsonl.gz`

For each dataset we should have a dataset card or datasheet in the same style has HuggingFace data cards https://huggingface.co/docs/hub/datasets-cards
I prefer to have the dataset cards on github to be able to track changes.
The data card contains a header in yaml to make it machine readable, which is then followed by descriptions in markdown.
I see that it can be a problem if the datasets contain sub-sources with different licenses for example. In that case the license field in the yaml could either be a dictionary that maps from sub-sources to a specific license, or the license field could be a keyword, e.g. `multiple` and then we add a "license" field in the "metadata" dictionary of each document. I think I will prefer the yaml dictionary approach, because the idea is that the datasheets makes it possible to select datasets based on the metadata without reading through the actual data first.

**Comment by peterbjorgensen** [comment]
We should also rearrange the conversion script, so they are in a separate directory and are named something like `dataformatting/{source}.py`, but I guess this is outside the scope of the validator.

**Comment by TTTTao725** [comment]
that's what I'm doing for dagw now:
<img width="389" alt="image" src="https://github.com/centre-for-humanities-computing/danish-foundation-models/assets/116294458/ca4e41d9-df8c-4e7c-802c-13ceb5c92078">

**Comment by KennethEnevoldsen** [comment]
@peterbjorgensen from this approach we would have to split up danish gigaword (due to multiple license). I think this approach is very reasonable though

**Comment by KennethEnevoldsen** [comment]
So the way I understand it now is:

pr dataset:
- conversion script called `{source}.py` located in `data-processing/scripts/convert_to_jsongz`
- metadata using the source above (without any license)
- datasheet with a yaml readable format, which has to include a license
- dataset located on ucloud

This would require us to split DAGW into subsegments due to licenses, but otherwise would allow us to combine datasets based on e.g. licenses easily.

**Comment by peterbjorgensen** [comment]
> So the way I understand it now is:
> 
> pr dataset:
> 
>     * conversion script called `{source}.py` located in `data-processing/scripts/convert_to_jsongz`
> 
>     * metadata using the source above (without any license)
> 
>     * datasheet with a yaml readable format, which has to include a license
> 
>     * dataset located on ucloud
> 
> 
> This would require us to split DAGW into subsegments due to licenses, but otherwise would allow us to combine datasets based on e.g. licenses easily.

Yes, sound good to me.

In case we want to support composite datasets, we could allow something like this in the yaml section, but it would be non-standard, so it might be better to split them up:
```
license:
     sub-source1: cc-by-sa-4.0
     sub-source2: cc0-1.0
     sub-source3: mit
```

**Comment by KennethEnevoldsen** [comment]
> but it would be non-standard, so it might be better to split them up:

I would probably split it as otherwise it will be hard to split them later on (if you don't know which subset has which license)

**Comment by KennethEnevoldsen** [comment]
Created an seperate issue for this
